services:
  - type: web
    name: my-playwright-app
    env: docker
    repo: https://github.com/echofsadness/my-express-bot
    region: singapore
    branch: main
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
